"""
Seeds the database with real 2024-2025 smartphones (Indian market prices).

Clears all existing products first, then inserts fresh data.

Run:
    docker-compose exec api python -m app.seed.seed_real_phones
"""
import asyncio

from sqlalchemy import text

from app.database import AsyncSessionLocal
from app.models.product import Product

# fmt: off
PHONES = [
    # ── Ultra Flagship ───────────────────────────────────────────────────────
    {
        "name":     "Samsung Galaxy S25 Ultra",
        "brand":    "Samsung",
        "category": "Phones",
        "price":    129999,
        "icon":     "📱",
        "quote":    "200 MP quad-camera beast powered by Snapdragon 8 Elite.",
        "aspects":  {"camera": 4.9, "battery": 4.6, "performance": 4.9,
                     "display": 4.9, "audio": 4.6, "build": 4.9, "value": 4.1},
        "pros":     ["Exceptional 200 MP camera with periscope zoom",
                     "Snapdragon 8 Elite — fastest Android chip",
                     "Titanium frame with premium Gorilla Glass Armor"],
        "cons":     ["Very expensive", "Large and heavy (218 g)",
                     "S Pen stylus limits battery space"],
        "highlights": ["200 MP main + 50 MP periscope 5× zoom",
                       "Snapdragon 8 Elite, 12 GB RAM",
                       "6.9-inch Dynamic AMOLED 2X, 120 Hz"],
    },
    {
        "name":     "Apple iPhone 16 Pro Max",
        "brand":    "Apple",
        "category": "Phones",
        "price":    144900,
        "icon":     "📱",
        "quote":    "Apple Intelligence meets the biggest Pro Max ever built.",
        "aspects":  {"camera": 4.8, "battery": 4.7, "performance": 4.9,
                     "display": 4.9, "audio": 4.7, "build": 4.9, "value": 4.0},
        "pros":     ["A18 Pro chip — class-leading CPU and GPU",
                     "4 685 mAh battery with best-ever iPhone endurance",
                     "Camera Control button for intuitive shooting"],
        "cons":     ["Very expensive", "iOS limits customisation",
                     "No charger included in box"],
        "highlights": ["A18 Pro chip with 6-core GPU",
                       "48 MP main + 12 MP ultrawide + 12 MP 5× telephoto",
                       "6.9-inch Super Retina XDR ProMotion, 1–120 Hz"],
    },
    {
        "name":     "Xiaomi 15 Ultra",
        "brand":    "Xiaomi",
        "category": "Phones",
        "price":    109999,
        "icon":     "📱",
        "quote":    "1-inch Leica sensor + 6 000 mAh battery redefine flagship photography.",
        "aspects":  {"camera": 4.9, "battery": 4.8, "performance": 4.9,
                     "display": 4.8, "audio": 4.5, "build": 4.8, "value": 4.3},
        "pros":     ["1-inch Leica Light Fusion 900 sensor",
                     "6 000 mAh battery with 90 W wired + 80 W wireless charging",
                     "Snapdragon 8 Elite, 16 GB RAM"],
        "cons":     ["Thick and heavy (226 g)", "MIUI software bloat",
                     "Limited availability outside China"],
        "highlights": ["50 MP 1-inch Leica main camera",
                       "6 000 mAh, 90 W wired + 80 W wireless + 10 W reverse",
                       "6.73-inch LTPO AMOLED, 1–120 Hz"],
    },
    # ── Flagship ─────────────────────────────────────────────────────────────
    {
        "name":     "Apple iPhone 16 Pro",
        "brand":    "Apple",
        "category": "Phones",
        "price":    119900,
        "icon":     "📱",
        "quote":    "Pro-grade A18 Pro performance in a more pocketable form.",
        "aspects":  {"camera": 4.8, "battery": 4.5, "performance": 4.9,
                     "display": 4.8, "audio": 4.7, "build": 4.9, "value": 4.1},
        "pros":     ["A18 Pro — fastest chip in any smartphone",
                     "ProRes video + Camera Control hardware button",
                     "Titanium design with Ceramic Shield front"],
        "cons":     ["Expensive", "Smaller battery than Pro Max",
                     "Limited USB-C transfer speed on base model"],
        "highlights": ["A18 Pro chip",
                       "48 MP main + 12 MP ultrawide + 12 MP 5× telephoto",
                       "6.3-inch Super Retina XDR ProMotion, 1–120 Hz"],
    },
    {
        "name":     "Samsung Galaxy S25+",
        "brand":    "Samsung",
        "category": "Phones",
        "price":    99999,
        "icon":     "📱",
        "quote":    "Slim Galaxy flagship with Snapdragon 8 Elite and vivid 6.7-inch display.",
        "aspects":  {"camera": 4.7, "battery": 4.6, "performance": 4.9,
                     "display": 4.8, "audio": 4.5, "build": 4.7, "value": 4.2},
        "pros":     ["Snapdragon 8 Elite — top-tier performance",
                     "4 900 mAh battery with all-day endurance",
                     "Slim 7.3 mm body with Galaxy AI features"],
        "cons":     ["Expensive", "No 200 MP camera like the Ultra",
                     "45 W charging is slower than Chinese rivals"],
        "highlights": ["Snapdragon 8 Elite, 12 GB RAM",
                       "50 MP main + 12 MP ultrawide + 10 MP 3× telephoto",
                       "6.7-inch Dynamic AMOLED 2X, 120 Hz"],
    },
    {
        "name":     "OnePlus 13",
        "brand":    "OnePlus",
        "category": "Phones",
        "price":    69999,
        "icon":     "📱",
        "quote":    "Hasselblad triple camera, 6 000 mAh, and Snapdragon 8 Elite at a sane price.",
        "aspects":  {"camera": 4.7, "battery": 4.8, "performance": 4.9,
                     "display": 4.8, "audio": 4.5, "build": 4.7, "value": 4.6},
        "pros":     ["6 000 mAh battery with 100 W fast + 50 W wireless charging",
                     "Hasselblad-tuned triple 50 MP camera system",
                     "Snapdragon 8 Elite with OxygenOS 15"],
        "cons":     ["Camera still behind Samsung/Apple flagships",
                     "Large 6.82-inch body not for everyone",
                     "No waterproofing rating for global model"],
        "highlights": ["50 MP main (Hasselblad) + 50 MP ultrawide + 50 MP 3× telephoto",
                       "6 000 mAh, 100 W SuperVOOC + 50 W wireless",
                       "6.82-inch LTPO4 AMOLED, 1–120 Hz"],
    },
    {
        "name":     "Google Pixel 9 Pro XL",
        "brand":    "Google",
        "category": "Phones",
        "price":    109999,
        "icon":     "📸",
        "quote":    "Google's biggest Pro — computational photography meets 7 years of updates.",
        "aspects":  {"camera": 4.9, "battery": 4.7, "performance": 4.7,
                     "display": 4.8, "audio": 4.6, "build": 4.8, "value": 4.2},
        "pros":     ["Best-in-class computational photography (Magic Eraser, Best Take)",
                     "5 060 mAh battery with 37 W fast charging",
                     "7 years of OS and security updates guaranteed"],
        "cons":     ["Tensor G4 slightly behind Snapdragon 8 Elite in raw performance",
                     "Expensive in India", "Gemini Nano AI features need internet"],
        "highlights": ["50 MP main + 48 MP ultrawide + 48 MP 5× telephoto",
                       "Tensor G4, 16 GB RAM",
                       "6.8-inch LTPO OLED, 1–120 Hz"],
    },
    {
        "name":     "Vivo X200 Pro",
        "brand":    "Vivo",
        "category": "Phones",
        "price":    94999,
        "icon":     "📱",
        "quote":    "200 MP periscope zoom and 6 000 mAh powered by Dimensity 9400.",
        "aspects":  {"camera": 4.9, "battery": 4.8, "performance": 4.8,
                     "display": 4.8, "audio": 4.4, "build": 4.7, "value": 4.3},
        "pros":     ["200 MP periscope telephoto — unmatched zoom clarity",
                     "6 000 mAh with 90 W fast + 30 W wireless charging",
                     "Dimensity 9400 — flagship-class performance"],
        "cons":     ["Funtouch OS can feel cluttered",
                     "Very heavy (229 g)", "Ultrawide below flagship rivals"],
        "highlights": ["50 MP main + 200 MP periscope 4× telephoto",
                       "6 000 mAh, 90 W wired + 30 W wireless",
                       "6.78-inch LTPO AMOLED, 1–120 Hz"],
    },
    # ── Upper Mid-range ───────────────────────────────────────────────────────
    {
        "name":     "Samsung Galaxy S25",
        "brand":    "Samsung",
        "category": "Phones",
        "price":    80999,
        "icon":     "📱",
        "quote":    "Compact Galaxy AI flagship that fits in any pocket.",
        "aspects":  {"camera": 4.6, "battery": 4.3, "performance": 4.9,
                     "display": 4.8, "audio": 4.5, "build": 4.7, "value": 4.3},
        "pros":     ["Snapdragon 8 Elite performance in a compact body",
                     "6.2-inch Dynamic AMOLED 2X with Galaxy AI",
                     "Slim 7.2 mm design"],
        "cons":     ["4 000 mAh battery is small for a 2025 flagship",
                     "Only 25 W charging", "No telephoto zoom lens"],
        "highlights": ["Snapdragon 8 Elite, 12 GB RAM",
                       "50 MP main + 12 MP ultrawide + 10 MP 3× telephoto",
                       "6.2-inch Dynamic AMOLED 2X, 120 Hz"],
    },
    {
        "name":     "Google Pixel 9",
        "brand":    "Google",
        "category": "Phones",
        "price":    79999,
        "icon":     "📸",
        "quote":    "Pure Android with Pixel's legendary camera smarts at a friendlier price.",
        "aspects":  {"camera": 4.7, "battery": 4.5, "performance": 4.6,
                     "display": 4.6, "audio": 4.5, "build": 4.6, "value": 4.4},
        "pros":     ["Pixel-exclusive AI camera (Night Sight, Photo Unblur)",
                     "4 700 mAh with clean Android 15",
                     "7 years of guaranteed OS updates"],
        "cons":     ["No telephoto camera unlike the Pro models",
                     "Tensor G4 behind Snapdragon 8 Elite",
                     "60 Hz-equivalent display (no LTPO)"],
        "highlights": ["50 MP main + 48 MP ultrawide",
                       "Tensor G4, 12 GB RAM",
                       "6.3-inch Actua OLED, 120 Hz"],
    },
    {
        "name":     "iQOO 13",
        "brand":    "iQOO",
        "category": "Phones",
        "price":    54999,
        "icon":     "📱",
        "quote":    "Snapdragon 8 Elite gaming flagship at a surprisingly aggressive price.",
        "aspects":  {"camera": 4.6, "battery": 4.8, "performance": 4.9,
                     "display": 4.8, "audio": 4.6, "build": 4.7, "value": 4.7},
        "pros":     ["Snapdragon 8 Elite with fastest UFS 4.0 storage",
                     "6 000 mAh + 120 W ultra-fast charging",
                     "144 Hz LTPO AMOLED with Monster Touch 2.0"],
        "cons":     ["Camera trails OnePlus 13 at same price",
                     "Funtouch OS / OriginOS not for everyone",
                     "Brand awareness lower than Samsung/Apple in India"],
        "highlights": ["Snapdragon 8 Elite, 12 GB RAM",
                       "6 000 mAh, 120 W wired + 30 W wireless",
                       "6.82-inch LTPO AMOLED, 144 Hz"],
    },
    # ── Mid-range ─────────────────────────────────────────────────────────────
    {
        "name":     "OnePlus 13R",
        "brand":    "OnePlus",
        "category": "Phones",
        "price":    42999,
        "icon":     "📱",
        "quote":    "Snapdragon 8 Gen 2 performance with a massive 5 500 mAh battery under ₹43 K.",
        "aspects":  {"camera": 4.4, "battery": 4.7, "performance": 4.7,
                     "display": 4.6, "audio": 4.4, "build": 4.5, "value": 4.7},
        "pros":     ["Snapdragon 8 Gen 2 — flagship-grade chip",
                     "5 500 mAh + 80 W SuperVOOC charging",
                     "6.78-inch 120 Hz AMOLED display"],
        "cons":     ["Camera mediocre for the price range",
                     "No telephoto lens", "Plastic frame on a premium mid-ranger"],
        "highlights": ["Snapdragon 8 Gen 2, 8/16 GB RAM",
                       "5 500 mAh, 80 W SuperVOOC",
                       "6.78-inch 120 Hz AMOLED"],
    },
    {
        "name":     "Realme GT 7 Pro",
        "brand":    "Realme",
        "category": "Phones",
        "price":    41999,
        "icon":     "📱",
        "quote":    "Snapdragon 8 Elite and 6 500 mAh at a mid-range price — a spec-sheet monster.",
        "aspects":  {"camera": 4.4, "battery": 4.8, "performance": 4.9,
                     "display": 4.7, "audio": 4.4, "build": 4.5, "value": 4.8},
        "pros":     ["Snapdragon 8 Elite — fastest chip in this price bracket",
                     "6 500 mAh + 120 W ultra-fast charging",
                     "IP69 dust and water resistance"],
        "cons":     ["Camera disappoints for the price",
                     "Realme UI still feels unpolished",
                     "Heavy at 223 g"],
        "highlights": ["Snapdragon 8 Elite, 12 GB RAM",
                       "6 500 mAh, 120 W SuperVOOC",
                       "6.78-inch LTPO AMOLED, 1–120 Hz"],
    },
    {
        "name":     "Motorola Edge 50 Pro",
        "brand":    "Motorola",
        "category": "Phones",
        "price":    31999,
        "icon":     "📱",
        "quote":    "125 W TurboPower charging and 144 Hz OLED in the cleanest Android under ₹35 K.",
        "aspects":  {"camera": 4.4, "battery": 4.5, "performance": 4.4,
                     "display": 4.7, "audio": 4.4, "build": 4.5, "value": 4.6},
        "pros":     ["125 W TurboPower — 4 500 mAh fully charged in ~32 min",
                     "144 Hz pOLED display — smoothest in segment",
                     "Near-stock Android 14 with 3 years of updates"],
        "cons":     ["Snapdragon 7 Gen 3 lags behind flagship chips",
                     "Camera struggles in low light",
                     "Build feels slightly plasticky"],
        "highlights": ["Snapdragon 7 Gen 3, 12 GB RAM",
                       "4 500 mAh, 125 W TurboPower",
                       "6.7-inch pOLED, 144 Hz"],
    },
    # ── Budget-Mid ────────────────────────────────────────────────────────────
    {
        "name":     "Nothing Phone (3a)",
        "brand":    "Nothing",
        "category": "Phones",
        "price":    29999,
        "icon":     "📱",
        "quote":    "50 MP dual telephoto and Glyph Interface in a phone that dares to be different.",
        "aspects":  {"camera": 4.5, "battery": 4.5, "performance": 4.2,
                     "display": 4.5, "audio": 4.4, "build": 4.5, "value": 4.7},
        "pros":     ["Dual 50 MP telephoto cameras — rare at this price",
                     "Unique Glyph Interface notification lights",
                     "Clean Nothing OS with 3 years of Android updates"],
        "cons":     ["Snapdragon 7s Gen 3 is only mid-tier",
                     "No IP rating", "Glyph novelty fades quickly"],
        "highlights": ["50 MP main + 50 MP 2× telephoto + 8 MP ultrawide",
                       "5 000 mAh, 50 W fast charging",
                       "6.77-inch AMOLED, 120 Hz"],
    },
    {
        "name":     "Redmi Note 14 Pro+ 5G",
        "brand":    "Xiaomi",
        "category": "Phones",
        "price":    26999,
        "icon":     "📱",
        "quote":    "200 MP camera and 6 000 mAh make this the budget king for spec hunters.",
        "aspects":  {"camera": 4.5, "battery": 4.8, "performance": 4.3,
                     "display": 4.5, "audio": 4.2, "build": 4.4, "value": 4.9},
        "pros":     ["200 MP Samsung ISOCELL HP3 main camera",
                     "6 000 mAh + 90 W HyperCharge",
                     "IP68 dust and water resistance"],
        "cons":     ["Dimensity 1400 Ultra is not a gaming chip",
                     "MIUI / HyperOS ads and bloatware",
                     "Low-light camera struggles despite high MP count"],
        "highlights": ["200 MP Samsung ISOCELL HP3 main camera",
                       "6 000 mAh, 90 W HyperCharge",
                       "6.67-inch AMOLED, 120 Hz, IP68"],
    },
    {
        "name":     "Apple iPhone 16",
        "brand":    "Apple",
        "category": "Phones",
        "price":    79900,
        "icon":     "📱",
        "quote":    "A18 chip and Apple Intelligence in the most accessible new iPhone.",
        "aspects":  {"camera": 4.6, "battery": 4.4, "performance": 4.8,
                     "display": 4.5, "audio": 4.6, "build": 4.7, "value": 4.2},
        "pros":     ["A18 chip — top-tier performance",
                     "Apple Intelligence AI features",
                     "Camera Control button for dedicated shooting"],
        "cons":     ["60 Hz OLED — no ProMotion unlike Pro models",
                     "3 561 mAh battery is small",
                     "No telephoto camera"],
        "highlights": ["A18 chip, 8 GB RAM",
                       "48 MP main + 12 MP ultrawide",
                       "6.1-inch Super Retina XDR OLED"],
    },
]
# fmt: on


async def seed() -> None:
    async with AsyncSessionLocal() as db:
        # Clear existing products and their reviews before inserting fresh data
        await db.execute(text("DELETE FROM reviews"))
        await db.execute(text("DELETE FROM products"))
        await db.commit()
        print("Cleared existing products and reviews.")

        for data in PHONES:
            db.add(
                Product(
                    name=data["name"],
                    brand=data["brand"],
                    category=data["category"],
                    price=data["price"],
                    icon=data["icon"],
                    quote=data["quote"],
                    aspects=data["aspects"],
                    pros=data["pros"],
                    cons=data["cons"],
                    highlights=data["highlights"],
                    rating=0.0,
                    review_count=0,
                    scores={},
                )
            )

        await db.commit()
        print(f"Inserted {len(PHONES)} real phones.")


if __name__ == "__main__":
    asyncio.run(seed())
